name: build-wheelhouse
on:
    push:
        tags:
            - 'v**'

env:
    PLATFORM: "win_amd64"
    PY_VERSION: "3.10"

jobs:
    build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v5
              with:
                python-version: $PY_VERSION
            - run: python build.py --platform $PLATFORM
            