name: build-wheelhouse
on:
    push:
        tags:
            - 'v**'
    workflow_dispatch:

env:
    PLATFORM: "win_amd64"

jobs:
    build:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v5
              with:
                python-version: "3.10"
            - run: python build.py --platform $PLATFORM
              working-directory: app
